export const ERROR_CODES = {
	VALIDATION_ERROR: "VALIDATION_ERROR",
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
